### ISSUE TITLE
可否设置监听127.0.0.1

### ISSUE THREAD

**Issue by mixool** [zhanghanyun/speedtest-rs#1]
写了个debian的脚本,觉得测速还是配合caddy自动tls,更符合实际使用情况,想让speedtest-rs只监听localhost
附上脚本地址:
https://github.com/mixool/across/blob/master/speedtest/speedtest-rs.sh

**Comment by zhanghanyun** [comment]
7e1e3b7bdc625411e5eab365dbda338ae0ed2a5e
